# -*- coding: utf-8 -*-
"""
Created on Sun Sep 22 13:13:01 2019

@author: Manas
"""

import numpy as np
'''
a=np.array([1,2,3])
print(a)
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype.name)
print(type(a))
b=np.array([['m','a','n','a','s',["kumar"]],[1,2,3]])
print(b)
print(b.shape)
print(b.ndim)
print(b.size)
print(b.dtype.name)
print(type(b))
'''
'''
a=np.array(['a','ab','abc'])
print(a)
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype.name)
print(type(a))
b=np.array([(1,2,3),(4,5,6)])
print(b)
print(b.shape)
print(b.ndim)
print(b.size)
print(b.dtype.name)
print(type(b))
print(b[0,2])
'''
'''
c=np.array([[1,2],[4,3]],dtype=complex)
print(c)
print(c.shape)
d=np.array([
        [[1,2,3],[4,5,6]],
        [[7,8,9],[10,11,12]]
            ])
print(d.shape)
print(d[0,1,2])
print(d)
#print(d.shape)
print(d.ndim)
print(d.size)
print(d.dtype.name)
print(type(d))
e=np.arange(7)
print(e)
f=np.random.random((3,3))
print(f)
g=np.ones((2,3))
print(g)
h=np.zeros((2,3))
print(h)
i=np.eye(4)
print(i)
'''
'''
a=np.linspace(1,2,4)
print(a)
b=np.full((1,2),10)
print(b)
c=np.arange(10,30,5)
print(c)
d=np.array([1,3,4],ndmin=3)
print(d)
print(d[0,0,1])
e=np.array([[1,2,3],[4,5,6]])
print(e.reshape(3,2))
'''

a=np.array([[1,2],[3,4],[5,6]])
boolean=(a>=3)
print(boolean)
print(a[~boolean])
print(a[boolean])
print(np.sum(a))
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))
print(a.T)

